spring:
  r2dbc:
    url: r2dbc:h2:file:///./build/test;MODE=MySQL;NON_KEYWORDS=USER
  flyway:
    url: jdbc:h2:file:./build/test;MODE=MySQL;NON_KEYWORDS=USER
    clean-disabled: false
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
  codec:
    max-in-memory-size: 16MB

server:
  forward-headers-strategy: FRAMEWORK
  error:
    whitelabel:
      enabled: false

slack:
  webhook: https://webhook.site/94fd9d96-9d9d-43b7-82c7-40bc3db39e77

mailgun:
  apiUrl: https://api.mailgun.net/v3/sandboxdb6d46dbc2954406a1e4b94104af6d4e.mailgun.org
  apiKey: key

cors:
  origins:
    - https://gh-stats.app
    - http://localhost:3000

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus