spring:
  r2dbc:
    url: r2dbc:h2:file:///./build/test
  flyway:
    url: jdbc:h2:file:./build/test

server:
  error:
    whitelabel:
      enabled: false

slack:
  webhook: https://webhook.site/94fd9d96-9d9d-43b7-82c7-40bc3db39e77

mailgun:
  apiUrl: https://api.mailgun.net/v3/sandboxdb6d46dbc2954406a1e4b94104af6d4e.mailgun.org
  apiKey: key