name: Build & Publish

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: '-Dfile.encoding=utf-8 -Dorg.gradle.daemon=false'

    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'
      - name: Test with Gradle
        run: ./gradlew check