name: Build & Publish
on:
  pull_request:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: ./gradlew build
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: flyctl deploy --remote-only
